### ISSUE TITLE
$id is not defined

### ISSUE THREAD

**Issue by tschoffelen** [craftcms/gatsby-source-craftcms#5]
Just started using this plugin, and it seems to be working really well. Was just wondering about this console error I saw, any idea why that's showing up?

![image](https://user-images.githubusercontent.com/666220/97785055-b0335600-1b9a-11eb-8d1b-6562b3402ac3.png)

**Comment by tschoffelen** [comment]
I think this might have had something to do with not having any content yet. I can't reproduce it now that there are entries in the Craft installation.

**Comment by andris-sevcenko** [comment]
Glad you got it working!
